parameters:
# xrowregexpline
    xrow_regexpline_types.xrowregexpline.class: xrow\XrowRegexplineBundle\FieldType\XrowRegexpline\Type
    xrow_regexpline_types.xrowregexpline.converter.class: xrow\XrowRegexplineBundle\FieldType\XrowRegexpline\XrowRegexplineConverter

services:
# xrowregexpline
    xrow_regexpline_types.xrowregexpline:
        class: %xrow_regexpline_types.xrowregexpline.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: xrowregexpline}
    xrow_regexpline_types.xrowregexpline.converter:
        class: %xrow_regexpline_types.xrowregexpline.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: xrowregexpline}